apiVersion: v1
kind: Service
metadata:
  name: ingressgateway-private
  annotations:
    istio: ingressgateway-private
{{- if .Values.private_ingress_custom_annotations }}
{{ .Values.private_ingress_annotation }}
{{- end }}
spec:
  type: LoadBalancer
  selector:
    app: istio-ingressgateway-private
  ports:
    - name: ingress-internal
      port: 80
      targetPort: 80
      nodePort: 31480
