---
# tasks file for istio
- name: tempating variables
  template:
    src: "{{ item }}.yaml"
    dest: "/tmp/{{item}}.yaml"
  with_items:
    - istio

- name: check helm release
  shell: "helm ls --all-namespaces | awk '{print $1}' | grep -E '^istio-init$'"
  register: output
  ignore_errors: true

- name: helm install
  shell: helm install istio-init {{ chart_path }}/istio --namespace istio-system -f /tmp/istio.yaml
  when: output.rc == 1

- name: helm upgrade
  shell: helm upgrade --cleanup-on-fail istio-init {{ chart_path }}/istio --namespace istio-system -f /tmp/istio.yaml
  when: output.rc == 0


- name: waiting for crds to get completed
  pause:
    seconds: 30

- name: Creating kiali secrtes
  shell:
    cmd: |
      cat <<EOF | kubectl apply -f -
      apiVersion: v1
      kind: Secret
      metadata:
        name: kiali
        namespace: istio-system
        labels:
          app: kiali
      type: Opaque
      data:
        username: "{{ 'admin' | b64encode }}"
        passphrase: "{{ grafana_admin_password | b64encode }}"
      EOF

- name: check helm release
  shell: "helm ls --all-namespaces | awk '{print $1}' | grep -E '^istio$'"
  register: output
  ignore_errors: true

- name: helm install
  shell: helm install istio {{ chart_path }}/istio --namespace istio-system -f /tmp/istio.yaml
  when: output.rc == 1

- name: helm upgrade
  shell: helm upgrade --cleanup-on-fail istio {{ chart_path }}/istio --namespace istio-system -f /tmp/istio.yaml
  when: output.rc == 0
