- name: rename template
  template:
    src: "{{ chart_path }}/values.j2"
    dest: "{{ chart_path }}/values.yaml"

- name: check helm release
  shell: helm ls --all-namespaces | awk '{print $1}' | grep -E "^{{ release_name }}$"
  register: output
  ignore_errors: true

- name: helm install
  shell: helm install {{ release_name }} {{ chart_path }} -n logging
  when: output.rc == 1

- name: helm upgrade
  shell: helm upgrade --recreate-pods {{ release_name }} {{ chart_path }} -n logging
  when: output.rc == 0
