---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-public-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: nginx-public-ingress
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-public-ingress
    spec:
{{- if .Values.imagepullsecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagepullSecrets }}
{{- end }}
      volumes:
        - name: tls
          secret:
            secretName: ingress-cert
        - name: tls-merge
          secret:
            secretName: ingress-merge-cert
        - name: proxy-config
          configMap:
            name: proxy-default
        - name: nginx-config
          configMap:
            name: nginx-conf
      containers:
      - name: name
        image: "{{ .Values.dockerhub }}/{{ .Values.repository }}:{{ .Values.image_tag }}"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - name: tls
            mountPath: /run/secrets
            readOnly: true
          - name: tls-merge
            mountPath: /run/secrets
            readOnly: true
          - name: proxy-config
            mountPath: /etc/nginx/conf.d
            readOnly: true
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-public-ingress
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nginx-public-ingress
  type: {{ .Values.service.type }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
