- name: rename template
  template:
    src: "{{ chart_path }}/values.j2"
    dest: "{{ chart_path }}/values.yaml"

- name: check helm release
  shell: helm ls --all-namespaces | awk '{print $1}' | grep -E "^{{ release_name }}$"
  register: output
  ignore_errors: true

- name: helm install
  shell: helm install {{ release_name }} {{ chart_path }} -n {{namespace}}
  when: output.rc == 1

- name: helm upgrade
  shell: helm upgrade --cleanup-on-fail {{ release_name }} {{ chart_path }} -n {{namespace}}
  when: output.rc == 0

- name: Get the deployment rollout status
  shell: "kubectl get deployments -A | grep -i {{ release_name }} | awk -F' ' '{print $3}' | awk -F/ '{if ($1 ~ $2){exit 0} else {exit 1}}'"
  register: task_result
  until: task_result.rc == 0
  retries: 6
  delay: 30

- name: Get deployed image name
  shell: "kubectl get deployments.apps {{ release_name }} -o json -n {{ namespace }} | jq '.spec.template.spec.containers | .[].image' -r | awk -F/ '{print $2}'"
  register: deployed_image

- set_fact:
   metadata_image: "{{ image_name }}:{{ image_tag }}"

- name: Compare deployed image and metadata_image
  fail:
  when: deployed_image.stdout != metadata_image
